site_name: BISCUIT Workshop
site_url: https://rom42pla.github.io/biscuit_workshop/
theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption